name: Spyros Lambrinidis
favicon: null
layout_spectrum: 0.22343580331653357
typography_spectrum: 0.0003893000539392233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.5625
  rhythmicContrast: 0.180559276137501
purpose: []
